### ISSUE TITLE
Conda installs incompatible version 4.0.1 for py2

### ISSUE THREAD

**Issue by fergalm** [conda-forge/timezonefinder-feedstock#22]
Issue:
I installed timezonefinder into my (fairly complicated) environment built around python 2.7, and I got version 4.0.1 by default. This version is incompatible with py2.7.  When I try to run my script (that depends on timezonefinder) I get the following message.

```
 python proximity.py         
Traceback (most recent call last):
  File "proximity.py", line 6, in <module>
    from timezonefinder import TimezoneFinder
  File "/home/fergal/apps/anaconda/envs/cdocker38/lib/python2.7/site-packages/timezonefinder/__init__.py", line 2, in <module>
    from .timezonefinder import TimezoneFinder
  File "/home/fergal/apps/anaconda/envs/cdocker38/lib/python2.7/site-packages/timezonefinder/timezonefinder.py", line 300
    def closest_timezone_at(self, *, lat, lng, delta_degree=1, exact_computation=False, return_distances=False,
```
I worked around the problem by specifying an earlier version 

   conda install timezonefinder=2.0.1

and the problem resolves itself. I suspect that the meta.yaml file for more recent versions of timezonefinder need to be updated to specify that python >=3 is required. 

<br/>
Environment (<code>conda list</code>):
Apologies... I didn't set up a small test case. I don't think the details of my environment are all that important, but here they are

<details>

```
$ conda list
# packages in environment at /home/fergal/apps/anaconda/envs/cdocker38:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5                        py_1    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
boto3                     1.10.15                    py_0    conda-forge
botocore                  1.13.15                    py_0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.11.28               py27_0    conda-forge
cffi                      1.13.2           py27h8022711_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
configparser              3.7.3                    py27_1    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
cryptography              2.8              py27h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
docutils                  0.15.2                   py27_0    conda-forge
entrypoints               0.3                   py27_1000    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
flake8                    3.7.8                    py27_1    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
futures                   3.3.0                    py27_0    conda-forge
gdal                      3.0.1            py27hbb6b9fb_9    conda-forge
geos                      3.7.2                he1b5a44_2    conda-forge
geotiff                   1.5.1                hfa9ff18_4    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py27_1000    conda-forge
importlib_metadata        0.23                     py27_0    conda-forge
importlib_resources       1.0.2                 py27_1000    conda-forge
ipaddress                 1.0.23                     py_0    conda-forge
ipdb                      0.12.2                     py_0    conda-forge
ipython                   5.8.0                    py27_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
kiwisolver                1.1.0            py27hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   3.0.1                hcf75f94_9    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.6.2             h303dfb8_1003    conda-forge
libopenblas               0.3.7                h6e990d7_2    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_1    conda-forge
libspatialite             4.3.0a            hcf5492f_1031    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                hee79883_5    conda-forge
llvmlite                  0.29.0           py27hd408876_0  
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
matplotlib                2.2.4                    py27_1    conda-forge
matplotlib-base           2.2.4            py27h250f245_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
more-itertools            4.3.0                 py27_1000    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numba                     0.45.1           py27h962f231_0  
numpy                     1.16.4           py27h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h21c5421_1    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.24.2           py27hb3f55d8_0    conda-forge
pathlib2                  2.3.5                    py27_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py27_0    conda-forge
pickleshare               0.7.5                 py27_1000    conda-forge
pillow                    6.2.1            py27h6b7be26_0    conda-forge
pip                       19.3.1                   py27_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
poppler                   0.67.0               ha967d66_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_1    conda-forge
proj                      6.2.0                hc80f0dc_1    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py27_1    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyproj                    1.9.4                    py27_0    conda-forge
pyqt                      5.9.2            py27hcca6a23_4    conda-forge
pysocks                   1.7.1                    py27_0    conda-forge
pytest                    4.6.4                    py27_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
qt                        5.9.7                h0c104cb_3    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
s3transfer                0.2.1                    py27_0    conda-forge
scandir                   1.10.0           py27h14c3975_0    conda-forge
scipy                     1.2.1            py27h921218d_2    conda-forge
setuptools                41.4.0                   py27_0    conda-forge
shapely                   1.6.4           py27hec07ddf_1006    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
sip                       4.19.8           py27hf484d3e_0  
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
subprocess32              3.5.4            py27h516909a_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.6.2                h69c774e_1    conda-forge
timezonefinder            2.0.1                    py27_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tornado                   5.1.1           py27h14c3975_1000    conda-forge
traitlets                 4.3.3                    py27_0    conda-forge
typing                    3.7.4.1                  py27_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.25.7                   py27_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : cdocker38
    active env location : /home/fergal/apps/anaconda/envs/cdocker38
            shell level : 2
       user config file : /home/fergal/.condarc
 populated config files : /home/fergal/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages :
       base environment : /home/fergal/apps/anaconda  (writable)
           channel URLs : http://api-oi-conda.dev.orbitalinsight.io/api/v1/package/linux-64
                          http://api-oi-conda.dev.orbitalinsight.io/api/v1/package/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/fergal/apps/anaconda/pkgs
                          /home/fergal/.conda/pkgs
       envs directories : /home/fergal/apps/anaconda/envs
                          /home/fergal/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/4.15.0-74-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by MrMinimal64** [comment]
thanks for reporting this.
yes, I am afraid this could be true.
since py2 is not being supported any more and older versions use outdated data, I wont fix this however. I am sorry.

**Comment by fergalm** [comment]
Hi,

Thanks for the response. I still think a fix to the *latest version* is necessary, and small. The promise of conda is that it will only install compatible software, but this promise is not being kept by timezonefinder. Because version 4 is not compatible with py2, the meta.yaml file should enforce this requirement, changing

` - python `
to
` - python > 3`

Then conda will only install the latest version of timezonefinder if py3 is in the environment, which is the correct behaviour. For people like me stuck in py2 environments (for reasons beyond my control), it is preferable for conda to refuse to install the latest version than to discover the incompatibility at run time.

No changes are necessary for the old versions.

**Comment by MrMinimal64** [comment]
Sorry I misunderstood. You are correct. this should be resolved!
I created a fix in a fork of mine, but I am not aware how to correctly create a pull request. Unfortunately I do not have time to read into the details of the conda procedure right now.
@snowman2 can you please jump in?

**Comment by snowman2** [comment]
@MrMinimal64 if you open up a PR I can comment on any changes needed.

**Comment by snowman2** [comment]
This should be addressed in the latest release.
